#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python



services: postgresql

env:
  - DJANGO=2.2.5

before_install:
  - export DJANGO_SETTINGS_MODULE=portfolio.settings
  - export PYTHONPATH=$HOME/builds/ishanExtreme/Portfolio
  - export PIP_USE_MIRRORS=true
install: # => 5
    - pip install -r requirements.txt 
before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py syncdb --noinput
