# Generated by Django 2.2.5 on 2020-01-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200130_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
